server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  ai:
    deepseek:
      base-url: https://yinli.one/v1
      chat:
        options:
          model: deepseek-chat
        api-key: sk-vir53o4YsOrBdAXZb236q1MwK16k0xy6nKLPVBtTSjc3uFxO

jwt:
  secret: asdfghjklzxcvbnmasdfghjklzxcvbnm123456
  expire: 72000000

alioss:
  access-key-id: ${OSS_ACCESS_KEY_ID}  # ??????????????
  access-key-secret: ${OSS_ACCESS_KEY_SECRET}
  bucket-name: java-web-itheima-zy
  endpoint: oss-cn-beijing.aliyuncs.com


